---
- name: Create wg container
  community.docker.docker_container:
    name: wg-easy
    image: ghcr.io/wg-easy/wg-easy:14
    sysctls:
      "net.ipv4.ip_forward": "1"
      "net.ipv4.conf.all.src_valid_mark": "1"
    capabilities:
      - NET_ADMIN
      - SYS_MODULE
    env:
      PASSWORD_HASH: "{{ wg_password }}"
      WG_HOST: "{{ ansible_default_ipv4.address }}"
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    volumes:
      - "/wg-easy/:/etc/wireguard"
    restart_policy: unless-stopped
