---
- name: Setup the homeserver
  hosts: all
  become: true

  tasks:
    - name: Perform essential tasks
      ansible.builtin.import_tasks: tasks/essential.yml
    - name: Install docker
      ansible.builtin.import_tasks: tasks/docker.yml
    - name: Install nginx
      ansible.builtin.import_tasks: tasks/nginx.yml
    - name: Install wireguard
      ansible.builtin.import_tasks: tasks/wg.yml
