---
- name: Setup the homeserver
  hosts: homeserver
  remote_user: root
  gather_facts: true
  become: true

  roles:
    - role: essential
    - role: docker
    - role: nginx
    - role: wireguard
