---
- name: Create nginx proxy manager container
  community.docker.docker_container:
    name: nginx-proxy-manager
    image: jc21/nginx-proxy-manager
    pull: true
    state: started
    restart_policy: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - "/nginx-proxy-manager/data:/data"
      - "/nginx-proxy-manager/letsencrypt:/etc/letsencrypt"
