---
- name: Update packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: safe
    autoremove: true

- name: Install required packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: false
  loop:
    - unzip
    - wget
    - curl
    - git
    - ranger
    - build-essential
    - python3
    - python3-pip
