---
- name: Update packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: safe
    autoremove: true
  when: ansible_os_family == "Debian"

- name: Install required packages
  ansible.builtin.package:
    name:
      - unzip
      - wget
      - curl
      - git
      - python3
      - python3-pip
    state: present
