---
- name: Set amd64 architecture
  set_fact:
    docker_arch: amd64
  when: ansible_architecture == "x86_64"

- name: Set arm64 architecture
  set_fact:
    docker_arch: arm64
  when: ansible_architecture == "aarch64" or ansible_architecture == "arm64"

- name: Install docker dependencies
  apt:
    name: "{{ docker_dependencies }}"
    state: latest

- name: Add docker gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repository
  apt_repository:
    repo: deb [arch={{ docker_arch }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Update apt and install docker
  block:
    - name: Attempt installation
      apt:
        update_cache: yes
        name: "{{ docker_packages }}"
        state: latest
  rescue:
    - name: Fix the dumb Ubuntu Jammy error
      replace:
        path: /etc/systemd/system/multi-user.target.wants/docker.service
        regexp: "fd://"
        replace: "unix://"
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version is version('22.04', '>=')

- name: Ensure docker group exists
  group:
    name: docker
    state: present

- name: Add user {{ username }} to docker group
  user:
    name: "{{ username }}"
    groups: docker
    append: yes

- name: Enable docker service
  service:
    name: docker
    enabled: yes
    state: started

- name: Create docker directory
  file:
    path: "{{ docker_dir }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
