---
- name: Create nginx directory
  file:
    path: "{{ docker_dir }}/nginx-proxy-manager/"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

- name: Create nginx proxy manager container
  docker_container:
    name: nginx-proxy-manager
    image: jc21/nginx-proxy-manager
    pull: yes
    state: started
    restart_policy: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - "{{docker_dir}}/nginx-proxy-manager/data:/data"
      - "{{docker_dir}}/nginx-proxy-manager/letsencrypt:/etc/letsencrypt"
